### ISSUE TITLE
use lightblue-camel?

### ISSUE THREAD

**Issue by dcrissman** [esbtools/event-handler#72]
There is a https://github.com/lightblue-platform/lightblue-camel project, I am curious if anything there could be re-used here OR if anything here could/should be moved there?

**Comment by alechenninger** [comment]
I don't think lightblue-camel is a good fit. We just use the lightblue client directly and it's worked pretty well.

**Comment by dcrissman** [comment]
I am still coming up to speed of course, and maybe this is me just being more curious than anything, but is there a way lightblue-camel could be improved?

LockingRoutePolicy and LightblueLockPolicy have probably the most obvious overlap, but certainly wouldn't be compelling enough by itself.

**Comment by alechenninger** [comment]
Last I looked I just didn't like that I had to set up lightblue requests to use outside of the code that used them. IMHO the lightblue client is a fine interface to lightblue already, there is not much to gain out of wrapping it in camel, since camel can already support arbitrary Java code as processors (rather nicely with Java 8 lambdas).

I think camel components are better suited to "dumb" async protocols like JMS, AMQP, Kafka, etc., where there will only be a few consumer or producer configurations in your application, and they aren't likely to be parameterized per message. For all the work to write a lightblue camel component, you can use a timer with a processor that uses the client just as well, and then you are free to use whatever timer implementation you need (whether the JDK timer or quartz, etc.).

There are a few camel abstractions that can be implemented, like route policies for locking, so I could see pulling those up, but not sure it's worth it for this project to have another dependency just for that one class.

**Comment by alechenninger** [comment]
Also, camel does encourage you to hide itself anyway, so I prefer to keep camel for plumping and write my own interfaces for our domain: http://camel.apache.org/hiding-middleware.html
